import {defineConfig} from 'vite';
import {resolve} from 'node:path';

const origin='https://brayroai.vercel.app';
const routeFiles={'/':'index.html','/plans':'plans.html','/clients':'clients.html','/clients/fakhrimart':'fakhrimart-case-study.html','/founder':'founder.html','/ai-workflow-audit':'ai-workflow-audit.html','/company-second-brain':'company-second-brain.html','/terms':'terms.html'};
const pathForFile=file=>Object.entries(routeFiles).find(([,name])=>file.endsWith(name))?.[0]||'/';
const nav=`<a class="brand" href="/" aria-label="BRAYROAI. home">BRAYRO<span>AI</span><span class="brand-dot" aria-hidden="true">.</span></a>
<nav class="desktop-nav" aria-label="Main navigation"><a href="/#work">Work</a><a href="/#approach">Approach</a><a href="/plans">Plans</a><a href="/founder">Founder</a></nav>
<div class="header-actions"><button class="market-button" type="button" data-market-open aria-haspopup="dialog" aria-controls="market-dialog">India · INR <span aria-hidden="true">⌄</span></button><a class="header-cta" href="/#contact">Start a project <span aria-hidden="true">↗</span></a><button class="menu-button" type="button" data-menu-open aria-label="Open menu" aria-haspopup="dialog" aria-controls="menu-dialog"><span></span><span></span></button></div>`;
const footer=`<footer class="footer premium-footer" id="site-footer"><div class="container premium-footer-grid"><div class="premium-footer-call"><p class="footer-kicker">BRAYROAI / PUNE · INDIA</p><h2>Have something<br><span>worth making?</span></h2><p>Start with the problem. Yash handles direction, interface and implementation from the first conversation through launch.</p><a class="footer-primary" href="mailto:yashganesh.work@gmail.com?subject=Start%20a%20project%20with%20BRAYROAI">Start a conversation <span aria-hidden="true">↗</span></a></div><div class="premium-footer-columns"><nav aria-label="Explore the site"><strong>EXPLORE</strong><a href="/#work">Selected work</a><a href="/clients">Client archive</a><a href="/#approach">How we work</a><a href="/plans">Plans</a><a href="/founder">Meet the founder</a></nav><nav aria-label="AI and details"><strong>AI &amp; DETAIL</strong><a href="/ai-workflow-audit">AI Workflow Audit</a><a href="/company-second-brain">Company Second Brain</a><a href="/terms">Terms</a><button type="button" data-rae-open>Ask Rae ↗</button></nav><div><strong>DIRECT CONTACT</strong><a href="mailto:yashganesh.work@gmail.com">Email Yash ↗</a><a href="https://wa.me/919175524637" target="_blank" rel="noreferrer">WhatsApp ↗</a><p>Working with ambitious teams from Pune, India.</p></div></div></div><div class="container premium-footer-word" aria-hidden="true">BRAYRO<span>AI</span></div><div class="container premium-footer-base"><span>© 2026 BRAYROAI · STRATEGY × CREATIVITY × REAL IMPACT</span><a href="#top">Back to top ↑</a></div></footer>`;
const dialogs=`<dialog id="menu-dialog" class="menu-dialog" aria-label="Site menu"><div class="dialog-head"><span>BRAYRO AI</span><button type="button" data-menu-close aria-label="Close menu">×</button></div><nav aria-label="Mobile navigation"><a href="/#work">Work</a><a href="/clients">Clients</a><a href="/#approach">Approach</a><a href="/plans">Plans</a><a href="/founder">Founder</a><a href="/#contact">Start a project</a></nav><button type="button" data-market-open>India · INR ⌄</button></dialog>
<dialog id="market-dialog" class="market-dialog" aria-labelledby="market-heading"><div class="dialog-head"><h2 id="market-heading">Your market</h2><button type="button" data-market-close aria-label="Close market selector">×</button></div><p>Choose the price book that applies to your enquiry.</p><div role="radiogroup" aria-label="Market and currency"><button type="button" role="radio" data-market-choice="in" aria-checked="true">India <span>INR</span></button><button type="button" role="radio" data-market-choice="ae" aria-checked="false">UAE <span>AED</span></button><button type="button" role="radio" data-market-choice="au" aria-checked="false">Australia <span>AUD</span></button></div></dialog>
<button class="rae-launcher" type="button" data-rae-open aria-label="Ask Rae, BRAYRO AI's AI assistant"><img src="/assets/rae-face.svg" alt="" width="46" height="46"></button>
<dialog id="rae-dialog" class="rae-dialog" aria-labelledby="rae-heading"><div class="dialog-head"><div><small>BRAYRO AI / YOUR STUDIO COMPANION</small><h2 id="rae-heading">Meet Rae<span aria-hidden="true">.</span></h2></div><button type="button" data-rae-close aria-label="Close Rae">×</button></div><div class="rae-intro"><div class="rae-actor" data-rae-actor aria-hidden="true"><img class="rae-face" src="/assets/rae-face.svg" alt="" width="100" height="100"></div><div class="rae-intro-copy"><span class="rae-kicker">HELLO, I'M RAE</span><p>Tell me what you are making. I can help you find the right starting point.</p></div></div><div class="rae-starts" aria-label="Ways Rae can help"><button type="button" data-rae-prompt="Help me plan a new website or digital product for my business."><span>01</span><strong>Plan a project with Rae</strong><i aria-hidden="true">↗</i></button><button type="button" data-rae-prompt="Compare BRAYRO AI's website and AI offers for me."><span>02</span><strong>Compare the offers</strong><i aria-hidden="true">↗</i></button><button type="button" data-rae-prompt="Show me verified BRAYRO AI client work and explain what was made."><span>03</span><strong>Explore real work</strong><i aria-hidden="true">↗</i></button></div><div class="rae-messages" role="log" aria-live="polite" aria-relevant="additions text"></div><p class="rae-status" role="status"></p><form class="rae-form"><label for="rae-input">ASK ANYTHING ABOUT THE STUDIO</label><div><textarea id="rae-input" name="message" rows="2" maxlength="1200" placeholder="What are you working on?"></textarea><button type="submit" aria-label="Send message to Rae">↑</button></div></form><div class="rae-dialog-foot"><span>RAE / AI ASSISTANT</span><a class="rae-fallback" href="mailto:yashganesh.work@gmail.com">Talk to Yash directly ↗</a></div></dialog>`;
function shell(){
 return {name:'living-sketchbook-html',transformIndexHtml(html,ctx){
  const route=pathForFile(ctx.filename||''),canonical=`${origin}${route}`;
  return html.replace('<!-- SHELL_HEADER -->',`<header class="site-header" id="top"><div class="container header-inner">${nav}</div></header>`)
   .replace('<!-- SHELL_FOOTER -->',footer)
   .replace('<!-- SHELL_DIALOGS -->',dialogs)
   .replace('</head>',`<link rel="preload" href="/fonts/manrope-latin-variable.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="/premium-shell.css"><link rel="canonical" href="${canonical}"><meta property="og:url" content="${canonical}"><meta name="x-brayro-commit" content="${process.env.VERCEL_GIT_COMMIT_SHA||process.env.GITHUB_SHA||'local'}"></head>`);
 }};
}
function cleanRoutes(server){server.middlewares.use((req,_res,next)=>{if(!req.url)return next();const url=new URL(req.url,'http://local');const path=url.pathname.replace(/\/$/,'')||'/';let prefix='';let route=path;if(path.startsWith('/ae/')||path==='/ae'){prefix='/ae';route=path.slice(3)||'/'}else if(path.startsWith('/au/')||path==='/au'){prefix='/au';route=path.slice(3)||'/'}const file=routeFiles[route];if(file){req.url=`/${file}${url.search}`;return next()}next()})}
function previewRoutes(server){server.middlewares.use((req,res,next)=>{
 if(!req.url)return next();
 const url=new URL(req.url,'http://local'),path=url.pathname.replace(/\/$/,'')||'/';
 if(path==='/api/market'){res.statusCode=200;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','private, no-store');res.end(JSON.stringify({country:null,market:'in',language:'en',source:'local-preview'}));return}
 const redirect=target=>{const [pathname,hash]=target.split('#');res.statusCode=308;res.setHeader('Location',pathname+url.search+(hash?'#'+hash:''));res.end()};
 if(path==='/ae/ar'||path.startsWith('/ae/ar/'))return redirect('/ae'+path.slice('/ae/ar'.length));
 let prefix='',route=path;
 if(path.startsWith('/ae/')||path==='/ae'){prefix='/ae';route=path.slice(3)||'/'}
 else if(path.startsWith('/au/')||path==='/au'){prefix='/au';route=path.slice(3)||'/'}
 const retired={'/case-studies/fakhrimart':'/clients/fakhrimart','/fakhrimart-case-study.html':'/clients/fakhrimart','/clients.html':'/clients','/founder.html':'/founder','/ai-workflow-audit.html':'/ai-workflow-audit','/company-second-brain.html':'/company-second-brain','/plans.html':'/plans','/terms.html':'/terms'};
 if(retired[route])return redirect(prefix+retired[route]);
 if(routeFiles[route])req.url=`${prefix}${route==='/'?'':route}/index.html${url.search}`;
 next();
})}
export default defineConfig({publicDir:'static',plugins:[shell(),{name:'preview-routes',configureServer:cleanRoutes,configurePreviewServer:previewRoutes}],build:{outDir:'dist',emptyOutDir:true,rollupOptions:{input:{home:resolve('index.html'),plans:resolve('plans.html'),clients:resolve('clients.html'),case:resolve('fakhrimart-case-study.html'),founder:resolve('founder.html'),audit:resolve('ai-workflow-audit.html'),brain:resolve('company-second-brain.html'),terms:resolve('terms.html')}}}});
