import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

const waitReady=async page=>{await page.goto('/',{waitUntil:'networkidle'});await page.waitForFunction(()=>document.body.classList.contains('hero-ready'));await page.waitForFunction(()=>document.body.classList.contains('experience-ready'))};
const scrollTo=async(page,selector)=>{await page.evaluate(selector=>{document.documentElement.style.scrollBehavior='auto';document.querySelector(selector)?.scrollIntoView({block:'start'})},selector);await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))))};
const serious=results=>results.violations.filter(item=>['serious','critical'].includes(item.impact));
const expectNoOverflow=async page=>expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);

test('opening and frozen hero remain intact',async({page})=>{await waitReady(page);await expect(page.locator('#top')).toContainText('Digital, designed');await expect(page.locator('#top')).toContainText('SCROLL TO SHAPE THE STORY');await expect(page.locator('#top img[src="/assets/hero-background.webp"]')).toHaveCount(1);await expect(page.locator('#top img[src="/assets/yash-cutout.webp"]')).toHaveCount(1)});

test('post-hero chapters tell the requested story in exact order',async({page})=>{await waitReady(page);const order=await page.locator('[data-scroll-chapter]').evaluateAll(nodes=>nodes.map(node=>node.id));expect(order).toEqual(['starting-point','difference','services','work','plans','studio','contact']);await expect(page.locator('#system')).toHaveCount(1);await expect(page.locator('[data-particle-field]')).toHaveAttribute('aria-hidden','true')});

test('homepage has no serious or critical accessibility violations',async({page})=>{await waitReady(page);const results=await new AxeBuilder({page}).analyze();expect(serious(results)).toEqual([])});

test('exact one-time and optional support prices are all visible',async({page})=>{await waitReady(page);await scrollTo(page,'#plans');const plans=page.locator('#plans');for(const text of ['Website Starter','₹2,599','Business Website','₹3,999','Custom Experience','₹5,999+','Launch','₹2,499/mo','Grow','Pro'])await expect(plans).toContainText(text);for(const oldPrice of ['₹9,999','₹17,999','₹25K–35K+'])await expect(plans).not.toContainText(oldPrice);await expect(plans).toContainText('Hosting, domains, paid tools, ecommerce, large content work, and advanced integrations are scoped separately.')});

test('plan and support actions use exact descriptive mail subjects',async({page})=>{await waitReady(page);const expected=['BRAYROAI Website Starter — ₹2,599','BRAYROAI Business Website — ₹3,999','BRAYROAI Custom Experience enquiry','Help me choose a BRAYROAI plan','BRAYROAI Launch support','BRAYROAI Grow support','BRAYROAI Pro support'];const subjects=await page.locator('#plans a[href^="mailto:"]').evaluateAll(links=>links.map(link=>new URL(link.href).searchParams.get('subject')));for(const subject of expected)expect(subjects).toContain(subject)});

test('capability selection is semantic and manual choice pauses auto-selection',async({page})=>{await waitReady(page);await scrollTo(page,'#services');const ai=page.locator('[data-capability="ai"]');await ai.click();await expect(ai).toHaveAttribute('aria-pressed','true');await expect(page.locator('[data-capability-title]')).toHaveText('AI Systems');await expect(page.locator('[data-capability-outcome]')).toHaveText('Remove friction where it counts.');await page.evaluate(()=>window.scrollBy(0,360));await page.waitForTimeout(250);await expect(ai).toHaveAttribute('aria-pressed','true')});

test('FakhriMart proof stays inspectable in desktop, mobile, and together views',async({page})=>{await waitReady(page);await scrollTo(page,'#work');const gallery=page.locator('[data-proof-gallery]');for(const [view,label] of [['desktop','Desktop'],['mobile','Mobile'],['together','Together']]){await page.getByRole('button',{name:label,exact:true}).click();await expect(gallery).toHaveAttribute('data-view',view)}await expect(page.locator('#work img[src="/assets/fakhrimart-case-desktop.png"]')).toHaveCount(1);await expect(page.locator('#work img[src="/assets/fakhrimart-case-mobile.png"]')).toHaveCount(1);for(const fact of ['Yarn wholesaler','Catalogue-led browsing','Desktop + mobile experience','Enquiry-led flow'])await expect(page.locator('#work')).toContainText(fact);await expect(page.locator('#work a[href="https://fakhriyarns.vercel.app/"]')).toHaveCount(1)});

test('theme choice is explicit and persists across reloads',async({page})=>{await waitReady(page);const toggle=page.locator('[data-theme-toggle]');await expect(page.locator('html')).toHaveAttribute('data-theme','dark');await toggle.click();await expect(page.locator('html')).toHaveAttribute('data-theme','light');await expect(toggle).toHaveAttribute('aria-pressed','false');await page.reload({waitUntil:'networkidle'});await expect(page.locator('html')).toHaveAttribute('data-theme','light')});

test('ambient animation can be paused without hiding the story',async({page})=>{await page.setViewportSize({width:1440,height:900});await waitReady(page);await scrollTo(page,'#starting-point');const toggle=page.locator('.chapter-rail [data-motion-toggle]');await toggle.click();await expect(toggle).toHaveAttribute('aria-pressed','true');await expect(page.locator('body')).toHaveClass(/motion-paused/);for(const section of ['#starting-point','#difference','#services','#work','#plans','#studio','#contact'])await expect(page.locator(section)).toBeVisible()});

test('mobile menu is keyboard usable and exposes canonical chapters',async({page})=>{await page.setViewportSize({width:390,height:844});await waitReady(page);const button=page.locator('[data-menu-button]');const box=await button.boundingBox();expect(box.width).toBeGreaterThanOrEqual(44);expect(box.height).toBeGreaterThanOrEqual(44);await button.click();await expect(button).toHaveAttribute('aria-expanded','true');await expect(page.locator('[data-mobile-menu] a[href="#starting-point"]')).toBeVisible();await page.keyboard.press('Escape');await expect(button).toHaveAttribute('aria-expanded','false')});

test('direct chapter hashes remain usable after enhancement',async({page})=>{await page.goto('/#plans',{waitUntil:'networkidle'});await page.waitForFunction(()=>document.body.classList.contains('experience-ready'));await expect.poll(()=>page.evaluate(()=>location.hash)).toBe('#plans');await expect.poll(()=>page.evaluate(()=>Math.abs(document.querySelector('#plans').getBoundingClientRect().top))).toBeLessThan(110)});

test('no-JavaScript mode keeps all facts, prices, proof, and contact actions',async({browser})=>{const context=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}});const page=await context.newPage();await page.goto('/',{waitUntil:'networkidle'});for(const section of ['#starting-point','#difference','#services','#work','#plans','#studio','#contact'])await expect(page.locator(section)).toBeVisible();await expect(page.locator('#plans')).toContainText('₹2,599');await expect(page.locator('#work')).toContainText('Yarn wholesaler');await expect(page.locator('#contact a[href^="mailto:"]').first()).toBeVisible();await expectNoOverflow(page);await context.close()});

test('WebGL initialization failure exposes the readable fallback',async({browser})=>{const context=await browser.newContext();await context.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(kind,...args){if(kind==='webgl')return null;return original.call(this,kind,...args)}});const page=await context.newPage();await waitReady(page);await scrollTo(page,'#starting-point');await expect(page.locator('body')).toHaveAttribute('data-particle-mode','fallback');await expect(page.locator('#starting-point')).toBeVisible();await context.close()});

test('reduced motion renders stable chapters and disables the canvas',async({browser})=>{const context=await browser.newContext({reducedMotion:'reduce',viewport:{width:1280,height:800}});const page=await context.newPage();await waitReady(page);await expect(page.locator('body')).toHaveAttribute('data-particle-mode','static');await expect(page.locator('[data-particle-field]')).toHaveCSS('display','none');for(const section of ['#starting-point','#difference','#services','#work','#plans','#studio','#contact'])await expect(page.locator(section)).toBeVisible();for(const item of await page.locator('.reveal-item').all())expect(Number(await item.evaluate(el=>getComputedStyle(el).opacity))).toBeGreaterThan(.9);await context.close()});

for(const [width,height] of [[1920,1080],[1440,900],[1366,768],[1024,768],[768,1024],[430,932],[390,844],[375,812],[360,800],[320,568]])test(`no horizontal overflow across the full film at ${width}x${height}`,async({page})=>{await page.setViewportSize({width,height});await waitReady(page);for(const section of ['#starting-point','#difference','#services','#work','#plans','#studio','#contact']){await scrollTo(page,section);await expectNoOverflow(page)}});

test('mobile uses normal flow with full-size controls',async({page})=>{await page.setViewportSize({width:390,height:844});await waitReady(page);await scrollTo(page,'#services');for(const selector of ['#starting-point .chapter-header','.capability-focus','.care-index header'])expect(await page.locator(selector).evaluate(el=>getComputedStyle(el).position)).not.toBe('sticky');for(const button of await page.locator('[data-capability]').all()){const box=await button.boundingBox();expect(box.height).toBeGreaterThanOrEqual(44)}await scrollTo(page,'#plans');for(const link of await page.locator('.scope-step>a').all()){const box=await link.boundingBox();expect(box.height).toBeGreaterThanOrEqual(44)}});

test('runtime produces no page errors during the complete scroll',async({page})=>{const errors=[];page.on('pageerror',error=>errors.push(error.message));await waitReady(page);for(const section of ['#starting-point','#difference','#services','#work','#plans','#studio','#contact']){await scrollTo(page,section);await page.waitForTimeout(80)}expect(errors).toEqual([])});
