import { test, expect } from '@playwright/test';

const ready=async page=>{await page.goto('/',{waitUntil:'networkidle'});await page.waitForFunction(()=>document.body.classList.contains('experience-ready'))};
const scrollTo=async(page,selector)=>{await page.evaluate(selector=>{document.documentElement.style.scrollBehavior='auto';document.querySelector(selector).scrollIntoView({block:'start'})},selector);await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))))};

test('native scrolling drives chapter progress without hijacking the document',async({page})=>{await ready(page);const before=await page.evaluate(()=>({overflow:getComputedStyle(document.documentElement).overflowY,height:document.scrollingElement.scrollHeight,viewport:innerHeight}));expect(before.overflow).not.toBe('hidden');expect(before.height).toBeGreaterThan(before.viewport*6);await scrollTo(page,'#difference');const progress=Number(await page.locator('#difference').evaluate(el=>getComputedStyle(el).getPropertyValue('--chapter-progress')));expect(progress).toBeGreaterThan(0)});

test('the rail and particle state follow the active chapter',async({page})=>{await page.setViewportSize({width:1440,height:900});await ready(page);for(const [section,state] of [['#starting-point','presence'],['#services','disciplines'],['#work','proof'],['#plans','scope'],['#contact','identity']]){await scrollTo(page,section);await expect(page.locator(`.chapter-rail a[href="${section}"]`)).toHaveClass(/is-active/);await expect(page.locator(section)).toHaveAttribute('data-particle-state',state)}});

test('all interactive state changes use real buttons and visible pressed states',async({page})=>{await ready(page);await scrollTo(page,'#services');await page.locator('[data-capability="product"]').focus();await page.keyboard.press('Enter');await expect(page.locator('[data-capability="product"]')).toHaveAttribute('aria-pressed','true');await scrollTo(page,'#work');await page.getByRole('button',{name:'Mobile',exact:true}).focus();await page.keyboard.press('Space');await expect(page.getByRole('button',{name:'Mobile',exact:true})).toHaveAttribute('aria-pressed','true')});

test('post-hero styles activate after the non-blocking load path',async({page})=>{await page.goto('/',{waitUntil:'domcontentloaded'});for(const id of ['post-fixes-styles','experience-styles'])expect(['print','all']).toContain(await page.locator(`#${id}`).getAttribute('media'));await page.waitForFunction(()=>document.body.classList.contains('experience-ready'));await expect(page.locator('#experience-styles')).toHaveAttribute('media','all');await expect(page.locator('#post-fixes-styles')).toHaveAttribute('media','all');await expect(page.locator('html')).toHaveAttribute('data-experience','enhanced')});

test('final contact resolves the story into a selectable direct email',async({page})=>{await ready(page);await scrollTo(page,'#contact');await expect(page.locator('#contact')).toContainText('Let’s make that first impression count.');await expect(page.locator('.final-wordmark')).toContainText('BRAYROAI');await expect(page.locator('.contact-email a')).toHaveText('yashganesh.work@gmail.com');await expect(page.locator('.contact-primary')).toHaveAttribute('href',/subject=Start%20a%20BRAYROAI%20project/)});
