import { test, expect } from '@playwright/test';

const ready=async page=>{await page.goto('/',{waitUntil:'networkidle'});await page.waitForFunction(()=>document.body.classList.contains('experience-ready'))};
const scrollTo=async(page,selector)=>{await page.evaluate(selector=>{document.documentElement.style.scrollBehavior='auto';document.querySelector(selector).scrollIntoView({block:'start'})},selector);await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))))};

test('native scrolling drives chapter progress without hijacking the document',async({page})=>{await ready(page);const before=await page.evaluate(()=>({overflow:getComputedStyle(document.documentElement).overflowY,height:document.scrollingElement.scrollHeight,viewport:innerHeight}));expect(before.overflow).not.toBe('hidden');expect(before.height).toBeGreaterThan(before.viewport*6);await scrollTo(page,'#difference');const progress=Number(await page.locator('#difference').evaluate(el=>getComputedStyle(el).getPropertyValue('--chapter-progress')));expect(progress).toBeGreaterThan(0)});

test('the rail and particle state follow the active chapter',async({page})=>{await page.setViewportSize({width:1440,height:900});await ready(page);for(const [section,state] of [['#starting-point','presence'],['#services','disciplines'],['#work','proof'],['#plans','scope'],['#contact','identity']]){await scrollTo(page,section);await expect(page.locator(`.chapter-rail a[href="${section}"]`)).toHaveClass(/is-active/);await expect(page.locator(section)).toHaveAttribute('data-particle-state',state)}});

test('the live particle HUD resolves with the scroll narrative',async({page})=>{await page.setViewportSize({width:1440,height:900});await ready(page);await scrollTo(page,'#difference');await expect(page.locator('body')).toHaveAttribute('data-signal-state','attention');await expect(page.locator('[data-signal-label]')).toContainText(/ATTENTION|DISCIPLINES/);await scrollTo(page,'#contact');await expect(page.locator('body')).toHaveAttribute('data-signal-state','identity');await expect(page.locator('[data-signal-label]')).toContainText('IDENTITY / RESOLVED')});

test('particle field visibly activates on the first move into the post-hero story',async({page})=>{await page.setViewportSize({width:1440,height:900});await ready(page);await page.mouse.wheel(0,120);await scrollTo(page,'#starting-point');await expect(page.locator('body')).toHaveClass(/post-hero-active/);await expect(page.locator('body')).toHaveAttribute('data-particle-mode',/webgl|fallback/);const mode=await page.locator('body').getAttribute('data-particle-mode');if(mode==='webgl'){await expect(page.locator('[data-particle-field]')).toHaveCSS('opacity','1');const state=await page.evaluate(()=>({width:window.__BRAYROAI__?.particle?.canvas?.width||0,count:window.__BRAYROAI__?.particle?.profile?.count||0,pair:window.__BRAYROAI__?.particle?.pair||''}));expect(state.width).toBeGreaterThan(0);expect(state.count).toBeGreaterThanOrEqual(4200);expect(state.pair).not.toBe('')}else{await expect(page.locator('[data-formation-word]')).toHaveCSS('background-image',/radial-gradient/);expect(Number(await page.locator('[data-particle-fallback]').evaluate(el=>getComputedStyle(el).opacity))).toBeGreaterThanOrEqual(.17)}});

test('chapters anticipate, reveal, hold and release instead of simply appearing',async({page})=>{await page.setViewportSize({width:1440,height:900});await ready(page);const phases=await page.evaluate(()=>{document.documentElement.style.scrollBehavior='auto';const chapter=document.querySelector('#difference'),top=scrollY+chapter.getBoundingClientRect().top;const sample=[];for(const y of [top-innerHeight*.82,top-innerHeight*.45,top+80,top+chapter.offsetHeight-innerHeight*.08]){scrollTo(0,y);window.__BRAYROAI__?.film?.update();sample.push(chapter.dataset.scenePhase)}return sample});expect(phases).toContain('approach');expect(phases).toContain('reveal');expect(phases).toContain('hold');expect(phases).toContain('release')});

test('headlines are genuinely scrub-revealed when their own edge enters the viewport',async({page})=>{await page.setViewportSize({width:1440,height:900});await ready(page);const headline=page.locator('#difference h2');await expect(headline).toHaveAttribute('data-scroll-reveal','headline');const supported=await page.evaluate(()=>CSS.supports('animation-timeline:view()'));if(!supported)return;const before=await headline.evaluate(el=>({opacity:Number(getComputedStyle(el).opacity),clip:getComputedStyle(el).clipPath}));expect(before.opacity).toBeLessThan(.15);expect(before.clip).toContain('100%');await scrollTo(page,'#difference');const after=await headline.evaluate(el=>({opacity:Number(getComputedStyle(el).opacity),clip:getComputedStyle(el).clipPath}));expect(after.opacity).toBeGreaterThan(.9);expect(after.clip).not.toContain('100%')});

test('particle story holds forms and visibly deforms between them',async({page})=>{await page.setViewportSize({width:1440,height:900});await ready(page);await page.mouse.wheel(0,120);await scrollTo(page,'#starting-point');const states=await page.evaluate(()=>{const particle=window.__BRAYROAI__.particle;if(!particle.gl)return{mode:particle.mode,word:document.querySelector('[data-formation-word]')?.textContent};const first=particle.getShape('presence'),second=particle.getShape('attention');particle.setNarrative(0,.08,true);const held={raw:particle.rawMorph,morph:particle.morph,phase:document.body.dataset.particleTransition};particle.setNarrative(0,.5,true);const transition={raw:particle.rawMorph,morph:particle.morph,phase:document.body.dataset.particleTransition};return{mode:particle.mode,held,transition,different:first[0]!==second[0]||first[1]!==second[1],word:document.querySelector('[data-formation-word]')?.textContent}});expect(states.word).toMatch(/IDEA|SEEN/);if(states.mode==='fallback')return;expect(states.held.morph).toBe(0);expect(states.held.phase).toBe('holding');expect(states.transition.raw).toBeCloseTo(.5,2);expect(states.transition.phase).toMatch(/deforming|reforming/);expect(states.different).toBe(true)});

test('all interactive state changes use real buttons and visible pressed states',async({page})=>{await ready(page);await scrollTo(page,'#services');await page.locator('[data-capability="product"]').focus();await page.keyboard.press('Enter');await expect(page.locator('[data-capability="product"]')).toHaveAttribute('aria-pressed','true');await scrollTo(page,'#work');await page.getByRole('button',{name:'Mobile',exact:true}).focus();await page.keyboard.press('Space');await expect(page.getByRole('button',{name:'Mobile',exact:true})).toHaveAttribute('aria-pressed','true')});

test('post-hero styles activate after the non-blocking load path',async({page})=>{await page.goto('/',{waitUntil:'domcontentloaded'});for(const id of ['post-fixes-styles','experience-styles','cinematic-styles'])expect(['print','all']).toContain(await page.locator(`#${id}`).getAttribute('media'));await page.waitForFunction(()=>document.body.classList.contains('experience-ready'));for(const id of ['experience-styles','post-fixes-styles','cinematic-styles'])await expect(page.locator(`#${id}`)).toHaveAttribute('media','all');await expect(page.locator('html')).toHaveAttribute('data-experience','enhanced')});

test('final contact resolves the story into direct WhatsApp and email paths',async({page})=>{await ready(page);await scrollTo(page,'#contact');await expect(page.locator('#contact')).toContainText('Let’s make that first impression count.');await expect(page.locator('.final-wordmark')).toContainText('BRAYROAI');await expect(page.locator('.contact-email a')).toHaveText('yashganesh.work@gmail.com');await expect(page.locator('.contact-primary')).toHaveAttribute('href',/wa\.me\/919175524637/);await expect(page.locator('.contact-secondary')).toHaveAttribute('href','/plans')});
