import { chromium } from '@playwright/test';
const base=process.env.BASE_URL||'http://127.0.0.1:4173';
const concurrency=Number(process.env.STRESS_CONCURRENCY||24),total=Number(process.env.STRESS_REQUESTS||600);
const routes=['/','/plans','/founder','/terms','/commercial-cut.css','/commercial-cut.js','/direction-pass.css','/direction-pass.js','/motion-v4.css','/motion-v5.css','/motion-v5.js','/motion-v6.css','/motion-v6.js','/art-direction-v7.css','/art-direction-v7.js','/plans-page.css','/plans-page.js','/founder-page.css','/founder-page.js','/terms-page.css','/terms-page.js','/scrollcraft.css','/scrollcraft.js','/assets/hero-background.webp','/assets/yash-cutout.webp','/assets/about-yash.webp','/assets/brayroai-cinematic-opening.mp4'];
const failures=[],timings=[];const assert=(c,m)=>{if(!c)failures.push(m)};
async function httpLoad(){let cursor=0;async function worker(){while(cursor<total){const i=cursor++;const route=routes[i%routes.length],start=performance.now();try{const r=await fetch(`${base}${route}`);await r.arrayBuffer();timings.push(performance.now()-start);if(!r.ok)failures.push(`HTTP ${r.status}: ${route}`)}catch(e){failures.push(`${route}: ${e.message}`)}}}await Promise.all(Array.from({length:concurrency},worker))}
async function clear(page){await page.evaluate(()=>{document.querySelectorAll('.opening-sequence,.scope-open,.founder-open').forEach(n=>n.remove());document.body.classList.remove('polish-opening','hf-intro-active')})}
async function scrollStorm(page,passes=3,steps=22){await page.evaluate(async({passes,steps})=>{document.documentElement.style.scrollBehavior='auto';for(let pass=0;pass<passes;pass++)for(let step=0;step<=steps;step++){const r=pass%2===0?step/steps:1-step/steps;scrollTo(0,(document.documentElement.scrollHeight-innerHeight)*r);if(step%4===0)await new Promise(requestAnimationFrame)}},{passes,steps})}
async function browserLoad(){const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:900}});const page=await context.newPage();const runtime=[];page.on('pageerror',e=>runtime.push(e.message));page.on('console',m=>{if(m.type()==='error')runtime.push(m.text())});
await page.goto(`${base}/`,{waitUntil:'networkidle'});await page.waitForSelector('[data-hf-intro-video]');assert(await page.locator('[data-hf-intro-video]').count()===1,'HyperFrames intro missing');await page.locator('[data-hf-skip]').click();await page.waitForTimeout(600);assert(await page.locator('[data-editorial-sequence] video').count()===0,'background film returned');
for(const vp of [{width:390,height:844},{width:1440,height:900},{width:1920,height:1080}]){await page.setViewportSize(vp);await page.goto(`${base}/`,{waitUntil:'networkidle'});await clear(page);await page.waitForSelector('link[data-art-direction-v7]',{state:'attached'});assert(await page.locator('[data-scene]').count()===7,`home scenes @${vp.width}`);assert((await page.locator('#plans').innerText()).includes('₹25K–₹35K+'),'homepage premium one-time tier missing');assert(await page.locator('.v7-browserbar').count()===1,'V7 work browser frame missing');assert(await page.locator('#plans .v7-recommended').count()===2,'V7 recommended pricing hierarchy missing');await scrollStorm(page)}
await page.goto(`${base}/plans`,{waitUntil:'networkidle'});await clear(page);await page.waitForSelector('link[data-art-direction-v7]',{state:'attached'});assert(await page.locator('[data-plan-scene]').count()===6,'plans scene count');assert(await page.locator('.build-card').count()===6,'plans card count');for(let i=0;i<80;i++){await page.locator(i%2?'[data-plan-mode="onetime"]':'[data-plan-mode="monthly"]').click()}assert(await page.locator('[data-plan-mode-output] strong').innerText()==='₹17,999','pricing mode director lost final one-time state');await scrollStorm(page);
await page.goto(`${base}/founder`,{waitUntil:'networkidle'});await clear(page);await page.waitForSelector('link[data-art-direction-v7]',{state:'attached'});for(let i=0;i<75;i++){const choices=page.locator('[data-principle]');await choices.nth(i%3).click()}assert((await page.locator('[data-principle-stage]').getAttribute('data-sc-verify-state'))==='principle:use','founder principle state');await scrollStorm(page);
await page.goto(`${base}/terms`,{waitUntil:'networkidle'});await page.waitForSelector('link[data-art-direction-v7]',{state:'attached'});assert(await page.locator('.terms-section').count()===12,'terms section count');await scrollStorm(page,2,18);assert((await page.locator('body').innerText()).includes('₹9,999'),'terms missing one-time pricing');assert((await page.locator('body').evaluate(n=>getComputedStyle(n).backgroundColor))==='rgb(236, 232, 223)','terms paper design missing');
failures.push(...runtime);await browser.close()}
const started=performance.now();await httpLoad();await browserLoad();timings.sort((a,b)=>a-b);const q=n=>timings[Math.min(timings.length-1,Math.floor(timings.length*n))]||Infinity;const summary={httpRequests:total,concurrency,routes:routes.length,pages:4,failures:failures.length,medianMs:Math.round(q(.5)),p95Ms:Math.round(q(.95)),elapsedMs:Math.round(performance.now()-started)};console.log(JSON.stringify(summary,null,2));if(summary.p95Ms>2200)failures.push(`HTTP p95 ${summary.p95Ms}ms exceeds 2200ms`);if(failures.length){console.error(failures.slice(0,30).join('\n'));process.exit(1)}console.log('Stress test passed: dual pricing, Terms, HyperFrames, Motion V6 and Art Direction V7 stayed coherent.');
